### ISSUE TITLE
infinite loop in foldtext for empty buffers

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/vim_dotfiles#2]
The lines

https://github.com/chrisbra/vim_dotfiles/blob/816a24ed81dccec04c82770834ca6c503665e3cd/plugin/CustomFoldText.vim#L6

gave an infinite loop for empty buffers, and
```vim
  "get first non-blank line
  let fs = nextnonblank(v:foldstart)

  while getline(fs) =~# '^\s\+$'
    let fs = nextnonblank(fs + 1)
  endwhile
```
helped me to fix it. 

After all, I am not sure why the loop is necessary, as`nextnonblank()` should return something that does not match ` '^\s\+$'`. Could you explain?

Your foldtext is at the base of

https://github.com/Konfekt/FoldText

**Comment by chrisbra** [comment]
Interesting. Yeah, that while condition does not make sense. that should probably be

```
let fs=nextnonblank(fs+1)
```

Does that brake anything for you?

**Comment by Konfekt** [comment]
You mean `let fs = nextnonblank(v:foldstart)` ? Let's give it a try in the weeks to follow.

**Comment by Konfekt** [comment]
Okay, as I read `:help nextnonblank()`, 
```vim
    if getline(fs) =~ '^\s*$'
      let fs = nextnonblank(fs + 1)
    endif
```
and 
```vim
let fs = nextnonblank(v:foldstart)
```
should yield the same.

**Comment by chrisbra** [comment]
yeah, mostlikely. Let me know if this breaks for you

**Comment by Konfekt** [comment]
Perhaps the original author @gregsexton could elucidate?
